### ISSUE TITLE
Enabling code splitting in production [Question]

### ISSUE THREAD

**Issue by Maushundb** [Alex-ray/v2-universal-js-hmr-ssr-react-redux#4]
Hey! I have a question about these lines in Routes.js
```
// For Development only
import * as RouteMap from 'universal/routes/static.js';

// This is used in production for code splitting via `webpack.config.server.js`
// import * as RouteMap from 'universal/routes/async.js';
```
It seems that using either one of them and commenting out the other works in both prod and dev. Could you explain how this works? I'm not seeing where it's used in webpack.config.server.js. Just want to make sure I'm getting code splitting running correctly.

**Comment by Alex-ray** [comment]
Ah yes, @Maushundb this very much a confusing part of the architecture and one that made me cringe when writing it... but it seems its the only way to enable both HMR and Code splitting at the moment.

Basically we do some tricky magic with a webpack plugin which you can view here https://github.com/Alex-ray/v2-universal-js-hmr-ssr-react-redux/blob/master/webpack/webpack.config.client.js#L54

We essentially just replace the URL, I just put the comment in there for context. I should probably go and clarify that 🤔

**Comment by Maushundb** [comment]
Ah that makes sense @Alex-ray! Thanks for the clarification. Thanks for the great repo btw, been learning a ton just poking around seeing how everything works!

**Comment by Alex-ray** [comment]
No problem @Maushundb , stoked to hear you enjoying the repo!

Definitley feel free to reach out, ask questions, make improvements etc 🙌
