### ISSUE TITLE
Unexpected character '@' 

### ISSUE THREAD

**Issue by strongharris** [Alex-ray/v2-universal-js-hmr-ssr-react-redux#6]
Hello

I'm trying to import Bootstrap CSS (global styling) in using this boilerplate. And it gives me this error ---

`Module parse failed: /Users/Harris/Desktop/alex/src/assets/css/theme-default/bootstrap.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @-webkit-keyframes fadeIn {
|   from {
|     opacity: 0;
 @ ./src/client/client.js 25:0-52
 @ multi babel-polyfill/dist/polyfill.js react-hot-loader/patch webpack-hot-middleware/client?noInfo=false ./client/client.js`

Do I have to tweak something in webpack? It seems like you set up everything correct. 

Sincerely,

**Comment by strongharris** [comment]
Also, if I would like to add an external stylesheet. Would I add it inside the Html.js?

**Comment by Alex-ray** [comment]
Hey @strongharris , there are a couple ways you could integrate bootstrap, my suggestion would be to follow the offical boostrap with webpack guide on the bootstrap project https://getbootstrap.com/docs/4.0/getting-started/webpack/ .

Yes, `Html.js` is where you would reference an external stylesheet. 🙂 

I hope this helps; let me know if you have any other issues!
